i=imread('doble.jpg');
r = i(:, :, 1);
g = i(:, :, 2);
b = i(:, :, 3);
figure;imshow(r);
figure;imshow(g);
figure;imshow(b);
ur = graythresh(i);
ug = graythresh(i);
ub = graythresh(i);
br=im2bw(r);
bg=im2bw(g);
bb=im2bw(b);
br=im2bw(r,ur);
bg=im2bw(g,ug);
bb=im2bw(b,ub);
figure;imshow(br);
figure;imshow(bg);
figure;imshow(bb);
figure;imshow(i);
